services:
  servermanagerbot:
    build: .
    restart: always
    env_file:
      - .env

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: "servermanagerbot"
      POSTGRES_USER: "botuser"
      POSTGRES_PASSWORD: "sm_bot_pass_2026"
      PGPORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
